# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration du nombre de workers
NUM_WORKERS = ENV['NUM_WORKERS'] || 2

Vagrant.configure("2") do |config|
    # Configuration commune
    config.vm.box = "ubuntu/jammy64"
    
    # Define master VM (Master)
    config.vm.define "master" do |master|
      master.vm.hostname = "master"
      master.vm.network "private_network", type: "dhcp"
      master.vm.network "forwarded_port", guest: 22, host: 2222, auto_correct: true
      
      master.vm.provider "virtualbox" do |v|
        v.name = "master"
        v.memory = 4096
        v.cpus = 2
      end

      master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      
      master.vm.provision "shell", path: "init_kubeadm.sh", env: { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
    end

    # Define Worker VMs avec numérotation dynamique
    (1..NUM_WORKERS.to_i).each do |i|
      config.vm.define "worker-#{i}" do |worker|
        worker.vm.hostname = "worker-#{i}"
        worker.vm.network "private_network", type: "dhcp"
        worker.vm.network "forwarded_port", guest: 22, host: "222#{i + 2}", auto_correct: true
        
        worker.vm.provider "virtualbox" do |v|
          v.name = "worker-#{i}"
          v.memory = 2048
          v.cpus = 1
        end

        worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        
        worker.vm.provision "shell", path: "init_kubeadm.sh", env: { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
      end
    end
  end