# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Configuration commune
    config.vm.box = "ubuntu/jammy64"
    
    # Define master VM (Master)
    config.vm.define "master" do |master|
      master.vm.hostname = "master"
      master.vm.network "private_network", type: "dhcp"
      
      master.vm.provider "virtualbox" do |v|
        v.name = "master"
        v.memory = 4096
        v.cpus = 2
      end

      # Partage du dossier pour la commande join
      master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      
      master.vm.provision "shell", path: "init_kubeadm.sh", env: { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
    end

    # Define Worker VM
    config.vm.define "worker" do |worker|
      worker.vm.hostname = "worker"
      worker.vm.network "private_network", type: "dhcp"
      
      worker.vm.provider "virtualbox" do |v|
        v.name = "worker"
        v.memory = 2048
        v.cpus = 1
      end

      # Partage du même dossier
      worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      
      worker.vm.provision "shell", path: "init_kubeadm.sh", env: { 'ENABLE_ZSH' => ENV['ENABLE_ZSH'] }
    end
  end